import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const poppin = Poppins({ weight: "500", subsets: ["latin"] });


import { Providers } from "./providers";
import { Toast } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";
import TopNavigationBar from "@/components/top-navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={poppin.className}>
        <Providers>
          <TopNavigationBar/>
          <main className="relative left-0 right-0 top-[54px]">
            {children}
          </main>
          <Toaster/>
        </Providers>

      </body>

    </html>

  );
}
